### ISSUE TITLE
Why does the browser open for so long?

### ISSUE THREAD

**Issue by andreirogal** [yashaka/selene#198]
Here is a simple project: https://github.com/andreirogal/selene-experiments
2 tests pass in **32 seconds**!
The first start is quick but after very slow.

On a native Selenium WebDriver all launches are fast.

**Comment by yashaka** [comment]
I can't reproduce the issue. On my side, with Mac OS Catalina, Chrome Version 79.0.3945.130 (Official Build) (64-bit) - everything is fine.

To reproduce, I have downloaded your project, added pyproject.toml 

```toml
[tool.poetry]
name = "selene-experiments"
version = "0.1.0"
description = ""
authors = ["andreirogal:"]

[tool.poetry.dependencies]
python = "^3.7"
selene = {version = "^2.0.0-alpha.21", allow-prereleases = true}

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
```

Then being inside project folder:
```
pyenv local 3.7.3
poetry install
poetry run py.test
```
And no any delay spotted. 

Total run on my side is "2 failed in 24.74 seconds", sometimes near 32s, yes, but I think this is fine taking into account that tests are slow themselves... Look at this video: 

https://youtu.be/ul-MbNJDobw

You can clearly see that opening browser takes near 4-5s, which is normal time as I remember... 
Then 5s is spent just for loading a page - something that is not influenced by selene or selenium... 
then near 2s we spent for actual test steps, then 2s for timeout waiting in assert, which is as expected, and maybe 1 second to close the browser. That's it - 15s for one test. Then we have another test with 15s more, where we come to near 30s total time execution which is normally fine in this case. 

Try to implement same test in raw selenium and show me that it will be faster. Of course it will be faster, because it does not have that selene dynamic smart logic of waiting, etc. But those places where you benefit from raw selenium webdriver are just 2s per test. So, if you make 1.5s for running test steps instead of 2s, this will not result much in total time execution, that is mainly affected by opening browser, loading google.com, and explicit waiting with timeout of 2s.
